### ISSUE TITLE
Static compilation

### ISSUE THREAD

**Issue by alexey-v-paramonov** [tangentsoft/mysqlpp#1]
Hello, I am trying to compile mysql++ statically this way:
`./configure LDFLAGS="-static"`

Result:
```
checking for MySQL C API library directory... no joy
configure: error: Didn't find mysqlclient library in '/usr/lib64 /usr/lib /usr/lib64/mysql /usr/lib/mysql /usr/local/lib64 /usr/local/lib /usr/local/lib/mysql /usr/local/mysql/lib /usr/local/mysql/lib/mysql /usr/mysql/lib/mysql /opt/mysql/lib /opt/mysql/lib/mysql /sw/lib /sw/lib/mysql'
````

config.log explaining this error attached.
[config.log](https://github.com/tangentsoft/mysqlpp/files/4884960/config.log)

Tried the latest Ubuntu and Alpine Linux Docker container.
MySQL static dev libraries are installed into the system.

**Comment by tangentsoft** [comment]
The point of that `config.log` file is for you to debug your problem locally. The relevant errors are usually near the end of the file. In this case, it's hundreds of errors beginning at line 7450:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libmysqlclient.a(libmysql.cc.o): in function `read_user_name(char*)':
(.text._Z14read_user_namePc+0x60): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

This is a local platform issue, not a MySQL++ issue.
