### ISSUE TITLE
Old release 3.2.5 and new release 3.2.5 differ

### ISSUE THREAD

**Issue by svenstaro** [tangentsoft/mysqlpp#10]
The old archive had the sha256sum `b780beeb3a9cd9ce6a9043028527484df8e822c58c5274d4d67ec5ba2fc0a778` while the new one has sha256sum `839cfbf71d50a04057970b8c31f4609901f5d3936eaa86dab3ede4905c4db7a8`. The difference seems to be only in documentation part. For posterity, this is the difference: [3.2.5.diff.gz](https://github.com/tangentsoft/mysqlpp/files/6394358/3.2.5.diff.gz)

Of course, the detected difference rang my alarm bells as I maintain this package in Arch Linux. The change does not appear to be malicious in nature but rather that you regenerated the documentation with a more recent version of oxygen in addition to some docs configuration changes.

I'd like to make you aware that re-releasing a package with the same exact version is generally frowned upon and should not be done. Usually, I believe it would be more advisable to merely cut a new patch release. As such, I'd like to ask you to create a new patch release.

**Comment by tangentsoft** [comment]
[Already discussed on the forum](https://tangentsoft.com/mysqlpp/forumpost/02aa29922f?t=h).

**Comment by svenstaro** [comment]
Alright, but could you please publish a new patch release?

**Comment by tangentsoft** [comment]
[3.3.0 is now released](https://tangentsoft.com/mysqlpp/doc/release/ChangeLog.md).
