### ISSUE TITLE
tcp address with '_', connect failed

### ISSUE THREAD

**Issue by MonstarCoder** [tangentsoft/mysqlpp#12]
in lib/tcp_connection.cpp/parse_address, "Ensure that there are only alphanumeric characters, dots, dashes and colons in address.  Anything else must be an error." 
But my host contains char '_', and mysqlpp connects to it fail, how can i fix it?

**Comment by tangentsoft** [comment]
Change your host name to [something legal](https://en.wikipedia.org/wiki/Hostname#Syntax). The fact that Windows tolerates underscores in DNS names is a nonstandard extension, one I'm not inclined to support in a portable library such as this.

If you want to carry a local patch that permits this, the library is open source under the LGPL. As long as you comply with its terms, you can modify the library to suit your needs.
