### ISSUE TITLE
Gigantic performance problem in do_conv

### ISSUE THREAD

**Issue by uNetworkingAB** [tangentsoft/mysqlpp#13]
If you fetch a big table of, say, integers then mysqlpp will choke on 100% CPU-time in do_conv. It's not exactly hard to guess why - you are constructing and destructing std::stringstream several times for every single row, and every single column.

We see a difference in CPU performance compared with libmariadb-dev that is 800% worse in mysqlpp in realtime, and 36000% worse in CPU-time.

**Comment by uNetworkingAB** [comment]
The vast majority of realtime is spent just spinning on CPU-time inside mysqlpp - if a query takes 16 seconds in total, only 2 seconds is actually spent in the DB, rest is just wasted in the connector.

**Comment by tangentsoft** [comment]
I have zero interest in optimizing this for you. If you want to send patches, then we can talk.

**Comment by uNetworkingAB** [comment]
No need, wrote a replacement library that cut load times in half. It's more of a hint for you.
