### ISSUE TITLE
Which function can be used to set ssl mode

### ISSUE THREAD

**Issue by zuige970126** [tangentsoft/mysqlpp#14]
We want to modify the value of ssl mode

**Comment by tangentsoft** [comment]
Set [`SslOption`](https://tangentsoft.com/mysqlpp/doc/html/refman/classmysqlpp_1_1SslOption.html) via a [connection option](https://tangentsoft.com/mysqlpp/doc/html/userman/tutorial.html#connopts).

We have documentation for a reason. Hint.

**Comment by zuige970126** [comment]
The option to set ssl mode is not used in SslOption.

**Comment by zuige970126** [comment]
I want to set up --ssl-mod = SSL_MODE_VERIFY_CA,

**Comment by tangentsoft** [comment]
> The option to set ssl mode is not used in SslOption.

If you trace the code, you find that it ends up calling [`mysql_ssl_set()`](https://dev.mysql.com/doc/c-api/5.7/en/mysql-ssl-set.html). What more do you want?

> I want to set up --ssl-mod = SSL_MODE_VERIFY_CA,

That's a `mysql` command option, not a MySQL Connector/C API, hence not something this library can wrap directly. You'd have to dig into the command line program's code to find out what it actually does underneath. However, I suspect that what you'll find is that it passes the "`ca`" option to `mysql_ssl_set()`, which my library's `SslOption` does allow.

**Comment by zuige970126** [comment]
Thank you very much for your answer
