### ISSUE TITLE
Bad URL in README.md 

### ISSUE THREAD

**Issue by tjanas** [tangentsoft/mysqlpp#15]
Update URL under Example Programs in [README.md](https://github.com/tangentsoft/mysqlpp/blob/trunk/README.md):

from
https://github.com/tangentsoft/mysqlpp/blob/trunk/doc/trunk/README-examples.txt
to
https://github.com/tangentsoft/mysqlpp/blob/trunk/README-examples.txt

**Comment by tangentsoft** [comment]
That's an artifact of the Fossil mirroring process. I suppose GitHub must have an equivalent of Fossil's `/doc` URL scheme, but to "fix" this URL I'd break it in Fossil.

The equivalent `README.md` file in the Fossil repo is [here](https://tangentsoft.com/mysqlpp/dir?ci=tip), and if you scroll down to the bottom and click the same link, you'll see that it does work.

As it says at the top of the same file, this mirror is "…intended for use by automation tooling based on Git." If you want to read the docs, go to the Fossil repo.

**Comment by tangentsoft** [comment]
I've made that URL absolute to force clicks from the GH mirror to go to the upstream Fossil repo. I've decided that this is fine for the top-level README, as a measure to direct interactive users across the boundary, but don't expect it for deeper links. Those will remain relative to the Fossil repo's URL scheme.
