### ISSUE TITLE
mysqlpp::Row operator = gives segmentation fault in threaded program

### ISSUE THREAD

**Issue by rossum2** [tangentsoft/mysqlpp#2]
The problem arises when I try to pass mysqlpp::Row as a parameter to a function. The library was compiled with thread awareness, mysqlpp::Connection::thread_start() is activated, the connection is properly grabbed by a derived class of mysqlpp::ConnectionPool. In the program some values are retrieved without any problems. Then a Row is passed to a function to be parsed and used. Here is the log from the gdb:

`Thread 4 "" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeffff700 (LWP 23828)]
0x00000000004abd5c in mysqlpp::RefCountedPointer<mysqlpp::SQLBuffer, mysqlpp::RefCountedPointerDestroyer<mysqlpp::SQLBuffer> >::~RefCountedPointer (
    this=0x7fffefffcd60, __in_chrg=<optimized out>)
    at /usr/local/include/mysql++/refcounted.h:129
129                     if (refs_ && (--(*refs_) == 0)) {
Missing separate debuginfos, use: yum debuginfo-install cryptopp-8.2.0-2.el8.x86_64 libgcc-8.3.1-5.el8.0.2.x86_64 libstdc++-8.3.1-5.el8.0.2.x86_64 mysql-libs-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 openssl-libs-1.1.1c-15.el8.x86_64 zlib-1.2.11-13.el8.x86_64
(gdb) backtrace 
#0  0x00000000004abd5c in mysqlpp::RefCountedPointer<mysqlpp::SQLBuffer, mysqlpp::RefCountedPointerDestroyer<mysqlpp::SQLBuffer> >::~RefCountedPointer (
    this=0x7fffefffcd60, __in_chrg=<optimized out>)
    at /usr/local/include/mysql++/refcounted.h:129
#1  0x00000000004ad703 in mysqlpp::RefCountedPointer<mysqlpp::SQLBuffer, mysqlpp::RefCountedPointerDestroyer<mysqlpp::SQLBuffer> >::assign (
    this=0x7fffe406c001, other=...)
    at /usr/local/include/mysql++/refcounted.h:164
#2  0x00000000004abea7 in mysqlpp::RefCountedPointer<mysqlpp::SQLBuffer, mysqlpp::RefCountedPointerDestroyer<mysqlpp::SQLBuffer> >::operator= (
    this=0x7fffe406c001, rhs=...)
    at /usr/local/include/mysql++/refcounted.h:184
#3  0x00000000004ab50d in mysqlpp::String::operator= (this=0x7fffe406c001, 
    other=...) at /usr/local/include/mysql++/mystring.h:483
#4  0x00000000004b2185 in std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<mysqlpp::String const*, mysqlpp::String*> (
    __first=0x7fffe4081010, __last=0x7fffe40810b0, __result=0x7fffe406c001)
    at /usr/include/c++/8/bits/stl_algobase.h:324
#5  0x00000000004b1c2c in std::__copy_move_a<false, mysqlpp::String const*, mysqlpp::String*> (__first=0x7fffe4081010, __last=0x7fffe40810b0, 
    __result=0x7fffe406c001) at /usr/include/c++/8/bits/stl_algobase.h:386
#6  0x00000000004b1456 in std::__copy_move_a2<false, __gnu_cxx::__normal_iterator<mysqlpp::String const*, std::vector<mysqlpp::String, std::allocator<mysqlpp::String> > >, mysqlpp::String*> (__first=
    {buffer_ = {counted_ = 0x7fffe4081690, refs_ = 0x7fffe40816d0}}, __last=
    {buffer_ = {counted_ = 0x7fffe40810c0, refs_ = 0x461}}, 
    __result=0x7fffe406c001) at /usr/include/c++/8/bits/stl_algobase.h:422
#7  0x00000000004b07c9 in std::copy<__gnu_cxx::__normal_iterator<mysqlpp::String const*, std::vector<mysqlpp::String, std::allocator<mysqlpp::String> > >, mysqlpp::String*> (__first=
    {buffer_ = {counted_ = 0x7fffe4081690, refs_ = 0x7fffe40816d0}}, __last=
    {buffer_ = {counted_ = 0x7fffe40810c0, refs_ = 0x461}}, 
    __result=0x7fffe406c001) at /usr/include/c++/8/bits/stl_algobase.h:455
#8  0x00000000004af0bb in std::vector<mysqlpp::String, std::allocator<mysqlpp--Type <RET> for more, q to quit, c to continue without paging--
::String> >::_M_assign_aux<__gnu_cxx::__normal_iterator<mysqlpp::String const*, std::vector<mysqlpp::String, std::allocator<mysqlpp::String> > > > (
    this=0x7fffe405d248, __first=
    {buffer_ = {counted_ = 0x7fffe4081690, refs_ = 0x7fffe40816d0}}, __last=
    {buffer_ = {counted_ = 0x7fffe40810c0, refs_ = 0x461}})
    at /usr/include/c++/8/bits/vector.tcc:308
#9  0x00000000004adbd0 in std::vector<mysqlpp::String, std::allocator<mysqlpp::String> >::_M_assign_dispatch<__gnu_cxx::__normal_iterator<mysqlpp::String const*, std::vector<mysqlpp::String, std::allocator<mysqlpp::String> > > > (
    this=0x7fffe405d248, __first=
    {buffer_ = {counted_ = 0x7fffe4081690, refs_ = 0x7fffe40816d0}}, __last=
    {buffer_ = {counted_ = 0x7fffe40810c0, refs_ = 0x461}})
    at /usr/include/c++/8/bits/stl_vector.h:1512
#10 0x00000000004ac173 in std::vector<mysqlpp::String, std::allocator<mysqlpp::String> >::assign<__gnu_cxx::__normal_iterator<mysqlpp::String const*, std::vector<mysqlpp::String, std::allocator<mysqlpp::String> > >, void> (
    this=0x7fffe405d248, __first=
    {buffer_ = {counted_ = 0x7fffe4081690, refs_ = 0x7fffe40816d0}}, __last=
    {buffer_ = {counted_ = 0x7fffe40810c0, refs_ = 0x461}})
    at /usr/include/c++/8/bits/stl_vector.h:656
#11 0x00000000004ab783 in mysqlpp::Row::operator= (this=0x7fffe405d238, 
    rhs=...) at /usr/local/include/mysql++/row.h:301`

**Comment by tangentsoft** [comment]
1. [Re]read [the user manual chapter on threading](https://tangentsoft.com/mysqlpp/doc/html/userman/threads.html).

2. Run your program under a thread debugger like [TSAN](https://clang.llvm.org/docs/ThreadSanitizer.html) or [Helgrind](https://www.valgrind.org/docs/manual/hg-manual.html).

3. If you can't fix the problem with advice from the manual or by fixing a bug in your code, then distill the problem to a program anyone can build and test. Preferably, modify one of the examples to show the behavior.
