### ISSUE TITLE
Build the library on centos(red hat)

### ISSUE THREAD

**Issue by yitian108** [tangentsoft/mysqlpp#8]
hi, when I try to find the configure file in the package, but it did not exist, how I build the source files to library?

I try to use autoconf to generate configure file, but when I use the command ./configure, the system prompted:

configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

is there any file or step be ignored?

**Comment by tangentsoft** [comment]
Read the README.md file.
