### ISSUE TITLE
forum post in https://tangentsoft.com/mysqlpp/forum get lost?

### ISSUE THREAD

**Issue by asmwarrior** [tangentsoft/mysqlpp#9]
Hi, I post a message in https://tangentsoft.com/mysqlpp/forum about two months ago. Here I asked a question about mysqlpp with the json. That post is in Awaiting Moderator Approval status, but now when I login to the forum and found that the post is missing now.

Is the post get deleted by the admin? I see recent message after mine are posted in the forum now, so any one can help me to recover that post in the https://tangentsoft.com/mysqlpp/forum, thanks.

**Comment by tangentsoft** [comment]
> about two months ago

I'm sure I've lost all memory and record of it then.

> I asked a question about mysqlpp with the json

MySQL++ doesn't have JSON features, so why would that be on-topic?

> Is the post get deleted by the admin?

Probably. The MySQL++ forum isn't a place for asking general how-to programming questions. It isn't even a place for asking MySQL or MariaDB questions that don't involve MySQL++ specific matters.

We only support MySQL++ proper on the forum, and here as well, for that matter.

**Comment by asmwarrior** [comment]
> 
> 
> > about two months ago
> 
> I'm sure I've lost all memory and record of it then.

At first I was thinking that the admin of forum was busy, so he may find some time to response to my message. So I just wait for a long time. Until now that I see other guys are posting messages in the forum, but my post just got lost. I think simply deleting a user's post without any response is not a good idea. 

> 
> > I asked a question about mysqlpp with the json
> 
> MySQL++ doesn't have JSON features, so why would that be on-topic?

In that message, I was asking some suggestion about how to use JSON combined with the mysqlpp. Though it's off-topic, but I did search the forum, and not found any topic about that. Maybe in the future, it could be added to mysqlpp.

> 
> > Is the post get deleted by the admin?
> 
> Probably. The MySQL++ forum isn't a place for asking general how-to programming questions. It isn't even a place for asking MySQL or MariaDB questions that don't involve MySQL++ specific matters.
> 
> We only support MySQL++ proper on the forum, and here as well, for that matter.

**Comment by tangentsoft** [comment]
> I was asking some suggestion about how to use JSON combined with the mysqlpp. 

Yes, and if you'd asked a question about how to use PHP to scrape XML data processed with XPath and inject it into MySQL with MySQL++, I'd also reject your question as not-on-topic.

It's quite simple: MySQL++ is a wrapper around the MySQL C API library. If you can do a thing with the `mysql` shell and/or the C API library, then you can probably get MySQL++ to present the resulting query data at the C++ level as well, but I'm not going to spend time digging down into these layers for you, any more than I'd help you debug `libc` or kernel problems.

If you can show me a C API program succeeding but MySQL++ crashing or whatever, *then* you've got something I can dig into.

I think you'll find that once you get the SQL working, you'll find that MySQL++ sees the result as just another rectangular data structure with columns and rows, so the existing examples will apply just fine.

> Maybe in the future, it could be added to mysqlpp.

MySQL++ is in maintenance mode indefinitely. I'll fix bugs and such, but I stopped adding new features years ago.

The path forward was intended to be [Libtabula](https://libtabula.org/), but no one seems interested in adopting it, so I lost interest in that as well. You're welcome to join in the development and resurrect the project, though.
